services:
  postgres:
    image: postgres:17
    container_name: ecommerce-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  redis:
    image: redis:8-alpine
    container_name: ecommerce-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
  order-service:
    build:
      context: ./services/order-service
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "8000:8000"
    env_file:
      - ./services/order-service/.env
    volumes:
      - ./services/order-service:/app
    depends_on:
      - postgres
      - redis
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload
volumes:
  postgres_data:
  redis-data:
networks:
  default:
    name: ecommerce-network